name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/

  functional_test:
    runs-on: ubuntu-latest
    container: node:20
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build/
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  security_test:
    runs-on: ubuntu-latest
    container: semgrep/semgrep:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep SAST
        run: |
          semgrep ci --config auto \
            --exclude "frontend/src/assets/private/**" \
            --sarif --output semgrep-results.sarif .
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-results.sarif
